services:

  postgres:
    image: postgres:16
    container_name: skills-postgres

    environment:
      POSTGRES_DB: course_recommendation_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U postgres -d course_recommendation_db"
        ]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

    networks:
      - skills-network


  backend:
    image: ghcr.io/ranaalsalahat/project3-backend:latest

  container_name: skills-backend

  environment:
    DB_HOST: postgres
    DB_PORT: 5432
    DB_NAME: course_recommendation_db
    DB_USER: postgres
    DB_PASSWORD: 123456

  depends_on:
    postgres:
      condition: service_healthy

    expose:
      - "5000"

    networks:
      - skills-network


  frontend:
    image: nginx:alpine
    container_name: skills-frontend

    ports:
      - "80:80"

    volumes:
      - ./frontend/static:/usr/share/nginx/html/static:ro
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf:ro

    depends_on:
      backend:
        condition: service_started

    networks:
      - skills-network


volumes:
  postgres_data:


networks:
  skills-network:
    driver: bridge
